const CoursesActionTypes = {
  GET_ACCESS_TOKEN: 'GET_ACCESS_TOKEN',
  GET_ACCESS_TOKEN_SUCCESS: 'GET_ACCESS_TOKEN_SUCCESS',
  GET_ACCESS_TOKEN_FAILURE: 'GET_ACCESS_TOKEN_FAILURE',

  FETCH_COURSES: "FETCH_COURSES",
  FETCH_COURSES_SUCCESS: "FETCH_COURSES_SUCCESS",
  FETCH_COURSES_FAILURE: "FETCH_COURSES_FAILURE",

  FETCH_COURSE_BY_ID: "FETCH_COURSE_BY_ID",
  FETCH_COURSE_BY_ID_SUCCESS: "FETCH_COURSE_BY_ID_SUCCESS",
  FETCH_COURSE_BY_ID_FAILURE: "FETCH_COURSE_BY_ID_FAILURE",

  UPDATE_TEXT: "UPDATE_TEXT",
  GET_TEXT: "GET_TEXT"
};

export default CoursesActionTypes;
